# Generated by Django 2.1.7 on 2020-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_campus_classe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
    ]
