# Generated by Django 2.2.10 on 2020-04-02 21:33

import cadastros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0003_auto_20200402_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('data_final', models.DateField(blank=True, help_text='Informar apenas se o comprovante for relativo a um período.', null=True)),
                ('arquivo', models.FileField(upload_to=cadastros.models.user_path)),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pontos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='campo',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nivel',
            field=models.IntegerField(verbose_name='nível'),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validado_em', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('justificativa', models.TextField(max_length=255)),
                ('comprovante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Comprovante')),
                ('validado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentado_em', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.CharField(blank=True, max_length=255, null=True)),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('siape', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Progressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('observacao', models.CharField(max_length=255, verbose_name='observação')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Classe')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comprovante',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Atividade'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='progressao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Progressao', verbose_name='progressão'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
