# Generated by Django 2.2.10 on 2020-04-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20200402_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Campus'),
            preserve_default=False,
        ),
    ]
