# Generated by Django 2.2.10 on 2020-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20200402_1927'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('numero', 'campo'), name='unica_num_atividade_campo'),
        ),
    ]
