# Generated by Django 2.2.10 on 2020-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20200402_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
