# Generated by Django 2.2.10 on 2020-04-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20200402_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
