# Generated by Django 2.2.11 on 2020-04-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20200402_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprovante',
            old_name='servidor',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='progressao',
            old_name='servidor',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='progressao',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Classe', verbose_name='classe pretendida'),
        ),
    ]
