# Generated by Django 2.2.12 on 2020-06-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200416_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
